Todolist-application-main/New_Todo/New_Todo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mytodo.urls'))
]

Todolist-application-main/New_Todo/mytodo/urls.py
from . import views
from django.urls import path

app_name = 'mytodo'


urlpatterns=[
    path('login/',views.loginpage, name ='login'),
    path('index/',views.index, name = 'index'),
    path('logout/',views.logoutpage, name = 'logout'),
    path('delete/<int:id>',views.delete_view,name = 'delete'),
    path('register/',views.registerpage,name = 'register'),
  
    
    ]

Todolist-application-main/New_Todo/mytodo/models.py
from django.db import models

# Create your models here.

class todo(models.Model):
    title = models.CharField(max_length=20)
    

    def __str__(self):
        return self.title

class signup_form(models.Model):
    username=models.CharField(max_length=20)
    password=models.CharField(max_length=10)

Todolist-application-main/New_Todo/mytodo/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

Todolist-application-main/New_Todo/mytodo/views.py
from django.shortcuts import render,redirect
from .models import todo
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from mytodo.forms import RegistrationForm




# Create your views here.

def registerpage(request):
    if request.method == "POST":
 
        form = RegistrationForm(request.POST)
 
        if form.is_valid():
            form.save()
             
            
            messages.success(request,f'a new user has been registered')
            return redirect('mytodo:login')


    else:
        form = RegistrationForm

        
    return render(request,'mytodo/registration.html',{'form':form})



def loginpage(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request,username=username,password=password)

    #    this is used to authenticate user
        if user is not None:
            login(request,user)
            return redirect('mytodo:index')

    return render(request,'mytodo/login.html')


def logoutpage(request):
    logout(request)
    return redirect('mytodo:login')


@login_required(login_url='mytodo:login')
def index(request):
    mytodo = todo.objects.all()
    
    if request.method == 'POST':
        if request.POST['title'].strip() == "":
            return redirect('mytodo:index')
        title = request.POST['title']
        new_todo = todo(title=title)
        new_todo.save()
        return redirect('mytodo:index')
    
    return render(request,'mytodo/index.html',{'mytodo':mytodo})



# the delete view makes use of GET methos because we are using 
# a dynamic url link to get 
# and delete object using thier id or pk

def delete_view(request,id):
    mytodo = todo.objects.get(id=id)
    if request.method == 'GET':
        mytodo.delete()
        return redirect('mytodo:index')
    

    
    
    
    

Todolist-application-main/New_Todo/mytodo/templates/mytodo/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<style>
    body{
        background-color: #F4F3EE;
    }
    main{
        max-width: 500px;
        /* width: 30%; */
        padding:15px;
        border: 1px solid beige;
        margin: auto;
        background-color: #BCB8B1;
    }

    #inputarea{
        width:85%;
        height: 5vh;
    }

    #logout{
        display: flex;
        text-decoration: none;
        margin: 10px;
        border: 1px solid grey;
        padding: 3px;
        width: 15%;
        justify-content: center;
        color: black;
        border-radius: 5px;
    }
    
    #logout:hover{

        background-color: #1B98E0;
    }

    #deletebutton{
        float: right;
        text-decoration: none;
        border: 1px solid  grey;
        padding: 3px;
        color: black;
        border-radius: 5px;
        background-color: #247BA0;
        color: azure;
    }


    #deletebutton:hover{
        background-color: #1B98E0;
    }

    li{
        margin-top: 15px;
    }

    .container{
        
    }
</style>
<body>
<main>
    <form  method="POST">
        {% csrf_token %}
       

        

        <div class="container">
            <input  type="textarea" name="title" id="inputarea">
            <button  type="submit" >Add</button>

            <a id="logout" href="{% url 'mytodo:logout' %}">logout</a>
        </div>

        
        <ul>

            {% for todo in mytodo reversed %}

               <li>{{todo.title|title }}<a class="fa fa-times" id="deletebutton" href="/delete/{{todo.id}}">Delete</a> </li>


            {% empty %}

               <h3>No items in list</h3>

         

            {% endfor %}


        </ul>

      




    </form>

</main>
    
</body>
</html>

Todolist-application-main/New_Todo/mytodo/templates/mytodo/login.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<style>
    #exampleInputEmail1{
        width: 90%;
    }

    #exampleInputPassword1{
        width: 90%;
    }

    main{
        max-width: 500px;
        /* width: 30%; */
        padding:15px;
        border: 1px solid #BCB8B1;
        margin: auto;
        background-color: #BCB8B1;
    }

    body{
        background-color: #F4F3EE;
    }


    
   
    
</style>
<body>
    <main>

    
    

<div class="container"> 

    <h3>LOGIN</h3>


        <form id="form" method="post">
            {% csrf_token %}
         
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Username</label>
              <input type="text" class="form-control" name="username" id="exampleInputEmail1" aria-describedby="emailHelp">
              
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password</label>
              <input type="password" class="form-control" name="password" id="exampleInputPassword1">
            </div>
            
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="{% url 'mytodo:register' %}">Dont have an account?Sign-up</a>
          </form>


    

</div>
 

</main>
</body>
</html>

Todolist-application-main/New_Todo/mytodo/templates/mytodo/registration.html
<h3>Register here</h3>
<hr>

<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit">Register</button>
    <a href="{% url 'mytodo:login' %}">Already have an account?Sign-in</a>
</form>